name: '9'
timestamp: 1541184823
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1541184822
positions:
  top-a: 'Top A'
  top-b: 'Top B'
  top-c: 'Top C'
  navigation-a: 'Navigation A'
  navigation-b: 'Navigation B'
  navigation-c: 'Navigation C'
  header-a: 'Header A'
  header-b: 'Header B'
  header-c: 'Header C'
  showcase-a: 'Showcase A'
  showcase-b: 'Showcase B'
  showcase-c: 'Showcase C'
  above-a: 'Above A'
  above-b: 'Above B'
  above-c: 'Above C'
  utility-a: 'Utility A'
  utility-b: 'Utility B'
  utility-c: 'Utility C'
  feature-a: 'Feature A'
  feature-b: 'Feature B'
  feature-c: 'Feature C'
  sidebar: Sidebar
  mainbar-a: 'Mainbar A'
  mainbar-b: 'Mainbar B'
  mainbar-c: 'Mainbar C'
  aside: Aside
  expanded-a: 'Expanded A'
  expanded-b: 'Expanded B'
  expanded-c: 'Expanded C'
  extension-a: 'Extension A'
  extension-b: 'Extension B'
  extension-c: 'Extension C'
  bottom-a: 'Bottom A'
  bottom-b: 'Bottom B'
  bottom-c: 'Bottom C'
  footer-a: 'Footer A'
  footer-b: 'Footer B'
  footer-c: 'Footer C'
  fixedside: 'Module Position'
sections:
  top: Top
  navigation: Navigation
  showcase: Showcase
  above: Above
  utility: Utility
  feature: Feature
  sidebar: Sidebar
  mainbar: Mainbar
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  fixedside: FixedSide
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-5900: 'System Messages'
    system-messages-9750: 'System Messages'
  position:
    position-8099: 'Top A'
    position-6306: 'Top B'
    position-5168: 'Top C'
    position-8094: 'Navigation A'
    position-4850: 'Navigation B'
    position-3443: 'Navigation C'
    position-3632: 'Header A'
    position-1537: 'Header B'
    position-1215: 'Header C'
    position-9740: 'Showcase A'
    position-4733: 'Showcase B'
    position-6057: 'Showcase C'
    position-2982: 'Above A'
    position-5890: 'Above B'
    position-7624: 'Above C'
    position-8510: 'Utility A'
    position-5782: 'Utility B'
    position-6814: 'Utility C'
    position-1296: 'Feature A'
    position-4458: 'Feature B'
    position-6978: 'Feature C'
    position-5978: Sidebar
    position-5330: 'Mainbar A'
    position-9053: 'Mainbar B'
    position-5373: 'Mainbar C'
    position-7991: Aside
    position-8265: 'Expanded A'
    position-3163: 'Expanded B'
    position-2940: 'Expanded C'
    position-7606: 'Extension A'
    position-2539: 'Extension B'
    position-6730: 'Extension C'
    position-7720: 'Bottom A'
    position-6848: 'Bottom B'
    position-6984: 'Bottom C'
    position-9454: 'Footer A'
    position-2732: 'Footer B'
    position-3972: 'Footer C'
    position-3652: 'Module Position'
    position-position-5848: 'Top A'
    position-position-8722: 'Top B'
    position-position-8156: 'Top C'
    position-position-9119: 'Navigation A'
    position-position-4710: 'Navigation B'
    position-position-4061: 'Navigation C'
    position-position-9913: 'Header A'
    position-position-9180: 'Header B'
    position-position-3841: 'Header C'
    position-position-6972: 'Showcase A'
    position-position-5101: 'Showcase B'
    position-position-6046: 'Showcase C'
    position-position-1522: 'Above A'
    position-position-3687: 'Above B'
    position-position-1862: 'Above C'
    position-position-6161: 'Utility A'
    position-position-7176: 'Utility B'
    position-position-8996: 'Utility C'
    position-position-2199: 'Feature A'
    position-position-3084: 'Feature B'
    position-position-8345: 'Feature C'
    position-position-7885: Sidebar
    position-position-3027: 'Mainbar A'
    position-position-2691: 'Mainbar B'
    position-position-7091: 'Mainbar C'
    position-position-9672: Aside
    position-position-9348: 'Expanded A'
    position-position-8314: 'Expanded B'
    position-position-7938: 'Expanded C'
    position-position-5364: 'Extension A'
    position-position-6834: 'Extension B'
    position-position-4227: 'Extension C'
    position-position-4931: 'Bottom A'
    position-position-8802: 'Bottom B'
    position-position-2595: 'Bottom C'
    position-position-7327: 'Footer A'
    position-position-5701: 'Footer B'
    position-position-1346: 'Footer C'
    position-position-8009: 'Module Position'
  logo:
    logo-7743: Logo
    logo-1902: Logo
    logo-3617: Logo
    logo-1377: Logo
    logo-9171: Logo
    logo-3895: Logo
    logo-9475: Logo
    logo-6146: Logo
  menu:
    menu-1237: Menu
    menu-8615: Menu
  content:
    system-content-1919: 'Page Content'
    system-content-5285: 'Page Content'
  horizontalmenu:
    horizontalmenu-9777: 'Horizontal Menu'
    horizontalmenu-2135: 'Horizontal Menu'
  social:
    social-3128: Social
    social-5665: Social
    social-1874: Social
    social-9402: Social
    social-2564: Social
    social-2300: Social
  branding:
    branding-6088: Branding
    branding-5099: Branding
  copyright:
    copyright-7827: Copyright
    copyright-6789: Copyright
  totop:
    totop-6010: 'To Top'
    totop-1050: 'To Top'
  mobile-menu:
    mobile-menu-5076: 'Mobile Menu'
    mobile-menu-9742: 'Mobile Menu'
inherit:
  default:
    top: top
    system-messages-5900: system-messages-5900
    position-8099: position-8099
    position-6306: position-6306
    position-5168: position-5168
    navigation: navigation
    logo-7743: logo-7743
    menu-1237: menu-1237
    position-8094: position-8094
    position-4850: position-4850
    position-3443: position-3443
    header: header
    position-3632: position-3632
    position-1537: position-1537
    position-1215: position-1215
    showcase: showcase
    position-9740: position-9740
    position-4733: position-4733
    position-6057: position-6057
    above: above
    position-2982: position-2982
    position-5890: position-5890
    position-7624: position-7624
    utility: utility
    position-8510: position-8510
    position-5782: position-5782
    position-6814: position-6814
    feature: feature
    position-1296: position-1296
    position-4458: position-4458
    position-6978: position-6978
    sidebar: sidebar
    position-5978: position-5978
    mainbar: mainbar
    position-5330: position-5330
    position-9053: position-9053
    position-5373: position-5373
    system-content-1919: system-content-1919
    aside: aside
    position-7991: position-7991
    expanded: expanded
    position-8265: position-8265
    position-3163: position-3163
    position-2940: position-2940
    extension: extension
    position-7606: position-7606
    position-2539: position-2539
    position-6730: position-6730
    bottom: bottom
    position-7720: position-7720
    position-6848: position-6848
    position-6984: position-6984
    footer: footer
    position-9454: position-9454
    position-2732: position-2732
    position-3972: position-3972
    logo-1902: logo-1902
    horizontalmenu-9777: horizontalmenu-9777
    social-3128: social-3128
    copyright: copyright
    branding-6088: branding-6088
    copyright-7827: copyright-7827
    totop-6010: totop-6010
    fixedside: fixedside
    logo-3617: logo-3617
    social-5665: social-5665
    position-3652: position-3652
    offcanvas: offcanvas
    logo-1377: logo-1377
    social-1874: social-1874
    mobile-menu-5076: mobile-menu-5076
    system-messages-9750: system-messages-5900
    position-position-5848: position-8099
    position-position-8722: position-6306
    position-position-8156: position-5168
    logo-9171: logo-7743
    menu-8615: menu-1237
    position-position-9119: position-8094
    position-position-4710: position-4850
    position-position-4061: position-3443
    position-position-9913: position-3632
    position-position-9180: position-1537
    position-position-3841: position-1215
    position-position-6972: position-9740
    position-position-5101: position-4733
    position-position-6046: position-6057
    position-position-1522: position-2982
    position-position-3687: position-5890
    position-position-1862: position-7624
    position-position-6161: position-8510
    position-position-7176: position-5782
    position-position-8996: position-6814
    position-position-2199: position-1296
    position-position-3084: position-4458
    position-position-8345: position-6978
    position-position-7885: position-5978
    position-position-3027: position-5330
    position-position-2691: position-9053
    position-position-7091: position-5373
    system-content-5285: system-content-1919
    position-position-9672: position-7991
    position-position-9348: position-8265
    position-position-8314: position-3163
    position-position-7938: position-2940
    position-position-5364: position-7606
    position-position-6834: position-2539
    position-position-4227: position-6730
    position-position-4931: position-7720
    position-position-8802: position-6848
    position-position-2595: position-6984
    position-position-7327: position-9454
    position-position-5701: position-2732
    position-position-1346: position-3972
    logo-3895: logo-1902
    horizontalmenu-2135: horizontalmenu-9777
    social-9402: social-3128
    branding-5099: branding-6088
    copyright-6789: copyright-7827
    totop-1050: totop-6010
    logo-9475: logo-3617
    social-2564: social-5665
    position-position-8009: position-3652
    logo-6146: logo-1377
    social-2300: social-1874
    mobile-menu-9742: mobile-menu-5076
