version: 2
preset:
  image: 'gantry-admin://images/layouts/error.png'
  name: _error
  timestamp: 1541184822
layout:
  /top/:
    -
      - system-messages-3753
    -
      - 'position-9904 33.3'
      - 'position-7747 33.3'
      - 'position-3854 33.3'
  /navigation/:
    -
      - 'logo-2076 25'
      - 'menu-1503 75'
    -
      - 'position-1785 33.3'
      - 'position-4301 33.3'
      - 'position-8755 33.3'
  /header/:
    -
      - 'position-5766 33.3'
      - 'position-3536 33.3'
      - 'position-7828 33.3'
  /showcase/:
    -
      - 'position-3475 33.3'
      - 'position-6265 33.3'
      - 'position-2557 33.3'
  /above/:
    -
      - 'position-5634 33.3'
      - 'position-7199 33.3'
      - 'position-1518 33.3'
  /utility/:
    -
      - 'position-3713 33.3'
      - 'position-4156 33.3'
      - 'position-6926 33.3'
  /feature/:
    -
      - 'position-5504 33.3'
      - 'position-8519 33.3'
      - 'position-7244 33.3'
    -
      - infolist-5120
  /container-1717/:
    -
      -
        'sidebar 20':
          -
            - position-4744
      -
        'mainbar 60':
          -
            - 'position-6690 33.3'
            - 'position-7362 33.3'
            - 'position-4149 33.3'
          -
            - system-content-8558
      -
        'aside 20':
          -
            - position-7162
  /expanded/:
    -
      - 'position-5293 33.3'
      - 'position-4933 33.3'
      - 'position-5715 33.3'
  /extension/:
    -
      - 'position-6951 33.3'
      - 'position-7131 33.3'
      - 'position-6977 33.3'
    -
      - infolist-9698
  /bottom/:
    -
      - 'position-8527 33.3'
      - 'position-8819 33.3'
      - 'position-5104 33.3'
  /footer/:
    -
      - 'position-9770 33.3'
      - 'position-4697 33.3'
      - 'position-2701 33.3'
    -
      - 'logo-2976 25'
      - 'horizontalmenu-7850 50'
      - 'social-1891 25'
  /copyright/:
    -
      - 'branding-7769 25'
      - 'copyright-9373 50'
      - 'totop-9014 25'
  /fixedside/:
    -
      - logo-2013
    -
      - social-8431
    -
      - position-1137
  offcanvas:
    -
      - logo-4285
    -
      - social-8421
    -
      - mobile-menu-1074
structure:
  top:
    type: section
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
  above:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  sidebar:
    type: section
  mainbar:
    type: section
  container-1717:
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  extension:
    type: section
    attributes:
      boxed: ''
  bottom:
    type: section
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  copyright:
    type: section
    attributes:
      boxed: ''
  fixedside:
    type: section
    title: FixedSide
    attributes:
      boxed: ''
content:
  system-messages-3753:
    layout: false
    block:
      variations: 'nomarginall nopaddingall'
  position-9904:
    title: 'Top A'
    attributes:
      key: top-a
    layout: false
  position-7747:
    title: 'Top B'
    attributes:
      key: top-b
    layout: false
  position-3854:
    title: 'Top C'
    attributes:
      key: top-c
    layout: false
  logo-2076:
    attributes:
      class: 'g-logo g-logo-alt'
      enabled: 0
      image: 'gantry-media://logo/logo-alt.png'
    layout: false
    block:
      class: hidden-phone
  menu-1503:
    attributes:
      enabled: 0
    layout: false
  position-1785:
    title: 'Navigation A'
    attributes:
      key: navigation-a
    layout: false
  position-4301:
    title: 'Navigation B'
    attributes:
      key: navigation-b
    layout: false
  position-8755:
    title: 'Navigation C'
    attributes:
      key: navigation-c
    layout: false
  position-5766:
    title: 'Header A'
    attributes:
      key: header-a
    layout: false
  position-3536:
    title: 'Header B'
    attributes:
      key: header-b
    layout: false
  position-7828:
    title: 'Header C'
    attributes:
      key: header-c
    layout: false
  position-3475:
    title: 'Showcase A'
    attributes:
      key: showcase-a
    layout: false
  position-6265:
    title: 'Showcase B'
    attributes:
      key: showcase-b
    layout: false
  position-2557:
    title: 'Showcase C'
    attributes:
      key: showcase-c
    layout: false
  position-5634:
    title: 'Above A'
    attributes:
      key: above-a
    layout: false
  position-7199:
    title: 'Above B'
    attributes:
      key: above-b
    layout: false
  position-1518:
    title: 'Above C'
    attributes:
      key: above-c
    layout: false
  position-3713:
    title: 'Utility A'
    attributes:
      key: utility-a
    layout: false
  position-4156:
    title: 'Utility B'
    attributes:
      key: utility-b
    layout: false
  position-6926:
    title: 'Utility C'
    attributes:
      key: utility-c
    layout: false
  position-5504:
    title: 'Feature A'
    attributes:
      key: feature-a
    layout: false
  position-8519:
    title: 'Feature B'
    attributes:
      key: feature-b
    layout: false
  position-7244:
    title: 'Feature C'
    attributes:
      key: feature-c
    layout: false
  infolist-5120:
    title: 'Whooops! Error!'
    attributes:
      class: 'g-layercontent noborder'
      infolists:
        -
          image: ''
          imageloc: left
          textstyle: header
          imagestyle: compact
          desc: 'Looks like something went wrong. Sorry!'
          tag: ''
          subtag: ''
          label: ''
          link: ''
          icon: ''
          readmoreclass: ''
          title: 'Whooops! Error!'
    layout: false
    block:
      variations: center
  position-4744:
    title: Sidebar
    attributes:
      key: sidebar
    layout: false
  position-6690:
    title: 'Mainbar A'
    attributes:
      key: mainbar-a
    layout: false
  position-7362:
    title: 'Mainbar B'
    attributes:
      key: mainbar-b
    layout: false
  position-4149:
    title: 'Mainbar C'
    attributes:
      key: mainbar-c
    layout: false
  system-content-8558:
    layout: false
    block:
      class: g-error
      variations: center
  position-7162:
    title: Aside
    attributes:
      key: aside
    layout: false
  position-5293:
    title: 'Expanded A'
    attributes:
      key: expanded-a
    layout: false
  position-4933:
    title: 'Expanded B'
    attributes:
      key: expanded-b
    layout: false
  position-5715:
    title: 'Expanded C'
    attributes:
      key: expanded-c
    layout: false
  position-6951:
    title: 'Extension A'
    attributes:
      key: extension-a
    layout: false
  position-7131:
    title: 'Extension B'
    attributes:
      key: extension-b
    layout: false
  position-6977:
    title: 'Extension C'
    attributes:
      key: extension-c
    layout: false
  infolist-9698:
    title: 'Nothing to See Here'
    attributes:
      class: 'g-layercontent noborder'
      infolists:
        -
          image: ''
          imageloc: left
          textstyle: header
          imagestyle: compact
          desc: 'Please use the navigation above or contact us to find what you are looking for.'
          tag: ''
          subtag: ''
          label: 'Contact Us'
          link: '#'
          icon: ''
          readmoreclass: ''
          title: 'Nothing to See Here'
    layout: false
    block:
      variations: 'center nomarginall nopaddingall'
  position-8527:
    title: 'Bottom A'
    attributes:
      key: bottom-a
    layout: false
  position-8819:
    title: 'Bottom B'
    attributes:
      key: bottom-b
    layout: false
  position-5104:
    title: 'Bottom C'
    attributes:
      key: bottom-c
    layout: false
  position-9770:
    title: 'Footer A'
    attributes:
      key: footer-a
    layout: false
    block:
      class: g-title-bordered
  position-4697:
    title: 'Footer B'
    attributes:
      key: footer-b
    layout: false
    block:
      class: g-title-bordered
  position-2701:
    title: 'Footer C'
    attributes:
      key: footer-c
    layout: false
    block:
      class: g-title-bordered
  logo-2976:
    attributes:
      class: 'g-logo g-logo-alt'
      image: 'gantry-media://logo/logo-alt.png'
    layout: false
  horizontalmenu-7850:
    title: 'Horizontal Menu'
    attributes:
      items:
        -
          text: Gantry
          link: 'http://www.gantry.org/'
          name: Gantry
        -
          text: Features
          link: 'http://docs.gantry.org/gantry5/basics/key-features'
          name: Features
        -
          text: Particles
          link: 'http://docs.gantry.org/gantry5/particles'
          name: Particles
        -
          text: Join
          link: 'http://www.rockettheme.com/join'
          name: Join
    layout: false
    block:
      class: g-horizontalmenu-block
      variations: center
  social-1891:
    layout: false
  branding-7769:
    attributes:
      content: 'Powered by <a href="http://www.gantry.org/" title="Gantry Framework" class="g-powered-by">Gantry<span class="hidden-tablet"> Framework</span></a>'
    layout: false
  copyright-9373:
    layout: false
  totop-9014:
    title: 'To Top'
    attributes:
      icon: 'fa fa-arrow-circle-o-up fa-2x'
      content: ''
    layout: false
  logo-2013:
    attributes:
      class: 'g-fixedside-logo g-logo-alt'
    layout: false
  social-8431:
    layout: false
  position-1137:
    title: 'Module Position'
    attributes:
      key: fixedside
    layout: false
  logo-4285:
    attributes:
      class: 'g-offcanvas-logo g-logo-alt'
    layout: false
    block:
      class: 'nomarginall nopaddingall'
  social-8421:
    layout: false
    block:
      class: 'nomarginall nopaddingall center'
  mobile-menu-1074:
    title: 'Mobile Menu'
    layout: false
