version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1541184822
layout:
  /top/:
    -
      - system-messages-4472
  /navigation/: {  }
  /header/: {  }
  /showcase/: {  }
  /above/: {  }
  /utility/: {  }
  /feature/:
    -
      - infolist-5107
  /container-9983/:
    -
      -
        'sidebar 20': {  }
      -
        'mainbar 60':
          -
            - system-content-9694
      -
        'aside 20': {  }
  /expanded/: {  }
  /extension/:
    -
      - infolist-8023
  /bottom/: {  }
  /footer/:
    -
      - 'custom-8724 50'
      - 'newsletter-4455 50'
  /copyright/:
    -
      - 'branding-9146 25'
      - 'copyright-4552 50'
      - 'totop-2076 25'
  /fixedside/:
    -
      - logo-8074
    -
      - social-5616
  offcanvas:
    -
      - logo-3787
    -
      - social-9848
structure:
  top:
    type: section
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
      class: 'box-darkgrey g-outer-box'
  above:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  sidebar:
    type: section
  mainbar:
    type: section
  container-9983:
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  extension:
    type: section
    attributes:
      boxed: ''
  bottom:
    type: section
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  copyright:
    type: section
    attributes:
      boxed: ''
  fixedside:
    type: section
    title: FixedSide
    attributes:
      boxed: ''
content:
  system-messages-4472:
    layout: false
    block:
      variations: 'nomarginall nopaddingall'
  infolist-5107:
    title: Offline
    attributes:
      class: 'g-layercontent noborder'
      infolists:
        -
          image: ''
          imageloc: left
          textstyle: header
          imagestyle: compact
          desc: 'Sorry, We are Down for Maintenance'
          tag: ''
          subtag: ''
          label: ''
          link: ''
          icon: ''
          readmoreclass: ''
          title: Offline
    layout: false
    block:
      variations: center
  system-content-9694:
    layout: false
  infolist-8023:
    title: 'Maintenance Mode'
    attributes:
      class: 'g-layercontent noborder'
      infolists:
        -
          image: ''
          imageloc: left
          textstyle: header
          imagestyle: compact
          desc: 'Sorry, our Website is Temporarily Down for Maintenance. Please Check Back Again Soon.'
          tag: ''
          subtag: ''
          label: 'Contact Us'
          link: '#'
          icon: ''
          readmoreclass: ''
          title: 'Maintenance Mode'
    layout: false
    block:
      variations: 'center nomarginall nopaddingall'
  custom-8724:
    title: 'About Kraken'
    attributes:
      html: "<h3 class=\"g-title\">About Kraken</h3>\nKraken is available for purchase or part of a club membership from RocketTheme, inclusive of the RocketLauncher, template, addons and sources."
    layout: false
    block:
      variations: g-title-bordered
  newsletter-4455:
    title: 'Subscribe Here'
    attributes:
      title: 'Subscribe Here'
      headtext: 'Subscribe to our newsletter and stay updated on the latest developments and special offers!'
      inputboxtext: 'Email Address'
      buttontext: Join
      uri: rocketthemeblog
      buttonclass: button-4
    layout: false
    block:
      variations: g-title-bordered
  branding-9146:
    attributes:
      content: 'Powered by <a href="http://www.gantry.org/" title="Gantry Framework" class="g-powered-by">Gantry<span class="hidden-tablet"> Framework</span></a>'
    layout: false
  copyright-4552:
    layout: false
  totop-2076:
    title: 'To Top'
    attributes:
      icon: 'fa fa-arrow-circle-o-up fa-2x'
      content: ''
    layout: false
  logo-8074:
    attributes:
      class: 'g-fixedside-logo g-logo-alt'
    layout: false
  social-5616:
    layout: false
  logo-3787:
    attributes:
      class: 'g-offcanvas-logo g-logo-alt'
    layout: false
    block:
      class: 'nomarginall nopaddingall'
  social-9848:
    layout: false
    block:
      class: 'nomarginall nopaddingall center'
